[package]
name = "role_kernels_decode"
version = "0.1.0"
edition = "2021"
publish = false

description = "Decode-phase optimized GPU kernels"

[dependencies]
cust = { path = "../cust", default-features = false, features = ["impl_half"] }
log = "0.4"

[dev-dependencies]
ndarray = "0.16"
ndarray-rand = "0.15"

[build-dependencies]
cuda_builder = { workspace = true, default-features = false, features = ["rustc_codegen_nvvm", "llvm19"] }
